package com.openwearableinsights.api.readiness.domain;

import java.time.Instant;
import java.util.List;

/**
 * A versioned, deterministic readiness score.
 *
 * <p>This is generated by deterministic, testable analytics code — never by an LLM.
 * The LLM may explain this score; it never invents or overrides it.
 *
 * <p>Every score exposes: inputs, provenance, baseline, factor contributions,
 * missing-data treatment, confidence, algorithm version, plain-language
 * explanation, and known limitations.
 */
public record ReadinessScore(
        int score,
        String algorithmVersion,
        boolean provisional,
        String baselinePeriod,
        String confidence,
        String dataQuality,
        List<FactorContribution> factors,
        String missingDataTreatment,
        String explanation,
        String limitations,
        Instant computedAt
) {
    /** v0.2: added the Body Battery factor (see ReadinessCalculator) and rebalanced Stress's weight. */
    public static final String ALGORITHM_VERSION = "0.2";

    public ReadinessScore {
        if (score < 0 || score > 100) {
            throw new IllegalArgumentException("Score must be 0-100, got: " + score);
        }
    }
}