#!/usr/bin/env python3
"""
Open Wearable Insights — Synthetic Data Generator

Generates SYNTHETIC wearable health data for development and testing.
NO REAL HEALTH DATA is used. All values are randomly generated within
physiologically plausible ranges.

Usage:
    python3 synthetic_generator.py [--days 30] [--output ./]

Outputs:
    synthetic-measurements.json  — synthetic time-series measurements
    synthetic-activity.fit       — real synthetic FIT fixture (not regenerated by this script; see generate_synthetic_fit)
"""

import argparse
import json
import os
import random
from datetime import datetime, timedelta, timezone

METRIC_TYPES = [
    ("hr", "bpm", 50, 180),
    ("hrv", "ms", 20, 120),
    ("rhr", "bpm", 45, 70),
    ("steps", "count", 0, 20000),
    ("calories", "kcal", 1500, 3500),
    ("stress", "score", 0, 100),
    ("spo2", "percent", 90, 100),
    ("respiration", "brpm", 10, 25),
]

SLEEP_STAGES = ["deep", "rem", "light", "awake"]


def generate_measurements(days: int) -> list[dict]:
    """Generate synthetic measurements for the given number of days."""
    measurements = []
    now = datetime.now(timezone.utc)
    for day in range(days):
        day_start = now - timedelta(days=day)
        for metric, unit, low, high in METRIC_TYPES:
            # 4 readings per day per metric
            for hour in range(0, 24, 6):
                t = day_start + timedelta(hours=hour)
                measurements.append({
                    "time": t.isoformat(),
                    "source_tz": "UTC",
                    "metric_type": metric,
                    "value": round(random.uniform(low, high), 1),
                    "unit": unit,
                    "source": "synthetic",
                })
        # Sleep session
        for stage in SLEEP_STAGES:
            t = day_start + timedelta(hours=2)
            measurements.append({
                "time": t.isoformat(),
                "source_tz": "UTC",
                "metric_type": "sleep_stage",
                "value": float(SLEEP_STAGES.index(stage)),
                "unit": "stage",
                "source": "synthetic",
            })
    return measurements


def generate_synthetic_fit(path: str) -> None:
    """
    No-op: synthetic-activity.fit is a real, parseable FIT binary built with
    the official Garmin FIT SDK encoder (Java-only API — no Python bindings
    used here), generated by SyntheticFitFixtureGenerator in the backend:
    services/api/src/test/java/com/openwearableinsights/api/connections/adapter/garmin/SyntheticFitFixtureGenerator.java

    Re-run that generator (its main method) to regenerate the fixture if
    the message mix ever needs to change. This function intentionally does
    not touch the file, so running this script never clobbers it with a
    placeholder.
    """
    if not os.path.exists(path):
        print(f"  (skipped: {path} — generate it via SyntheticFitFixtureGenerator.main() instead)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Synthetic data generator")
    parser.add_argument("--days", type=int, default=30, help="Number of days")
    parser.add_argument("--output", default="./", help="Output directory")
    args = parser.parse_args()

    random.seed(42)  # Deterministic for golden tests

    measurements = generate_measurements(args.days)
    json_path = f"{args.output}synthetic-measurements.json"
    with open(json_path, "w") as f:
        json.dump(measurements, f, indent=2)
    print(f"✓ Generated {len(measurements)} synthetic measurements → {json_path}")

    fit_path = f"{args.output}synthetic-activity.fit"
    generate_synthetic_fit(fit_path)
    print(f"✓ Generated synthetic FIT fixture → {fit_path}")


if __name__ == "__main__":
    main()