package com.openwearableinsights.api.insights.application;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.openwearableinsights.api.insights.application.DeterministicInsightEngine.FactorSummary;
import com.openwearableinsights.api.insights.application.DeterministicInsightEngine.Insight;
import com.openwearableinsights.api.readiness.domain.ReadinessScore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.util.Locale;
import java.util.Optional;
import java.util.StringJoiner;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

/**
 * Optional local-LLM rephrasing of the deterministic daily insight — backs
 * docs/product/release-plan.md Phase 1 acceptance criteria #10/#11
 * ("optionally produces a local Ollama explanation" / "works when Ollama is
 * unavailable") and {@code owi.llm.enabled} (see {@code CoachController}).
 *
 * <p><b>Strictly a phrasing layer, never a second source of facts:</b> the
 * LLM is given the already-computed {@link ReadinessScore}'s score, headline,
 * factor contributions, and confidence, and asked to rewrite ONLY the
 * summary sentence in a warmer coaching voice — citing the same facts already
 * given, never a new number, factor, or claim. This is not a stylistic
 * preference: {@code ReadinessScore}'s own class javadoc states the
 * project's core principle ("generated by deterministic, testable analytics
 * code — never by an LLM. The LLM may explain this score; it never invents
 * or overrides it") and {@code DeterministicInsightEngine}'s own javadoc
 * repeats it. Every other field on the returned {@link Insight}
 * (headline/factors/confidence/cautions/limitations) is copied verbatim from
 * the deterministic engine's own output — only {@code summary} can differ.
 *
 * <p><b>Talks to Ollama's REST API directly, not via Spring AI's {@code
 * ChatClient}:</b> a deliberate choice, made after live-testing this session
 * against a real local Ollama 0.32.15 server + the configured default model
 * (qwen3:8b — the {@code OWI_LLM_MODEL} default in {@code application.yml}).
 * Qwen3 models "think" (an internal chain-of-thought, 900+ tokens observed
 * live) before answering by default, which is wildly disproportionate for a
 * one-sentence rephrase — a first attempt at suppressing it via a {@code
 * /no_think} prompt-level directive (Qwen3's own documented convention)
 * measurably helped but did not reliably eliminate it. Ollama's own {@code
 * /api/chat} added a native {@code "think": false} request field for exactly
 * this, which reliably works — but Spring AI 1.0.1's {@code OllamaOptions}
 * has no field for it and no generic passthrough for undocumented Ollama
 * options (confirmed by inspecting its full field list), so it cannot be
 * expressed through {@code ChatClient} at all. A plain {@link RestClient}
 * call to {@code /api/chat} with the real JSON field {@code "think": false}
 * is the only way to reliably suppress it at this Spring AI version. This is
 * a real, disclosed architectural deviation from the originally-planned
 * Spring AI integration, not an oversight — if Spring AI later exposes
 * {@code think} on {@code OllamaOptions}, switching back to {@code
 * ChatClient} would remove this class's main reason for existing in its
 * current form.
 *
 * <p><b>Live-verified this session</b> (not merely unit-tested against
 * mocks): a real local Ollama 0.32.15 server was brought up via {@code
 * infrastructure/docker/docker-compose.yml}'s optional {@code llm} profile,
 * {@code qwen3:8b} was pulled, and real requests through this exact class
 * were confirmed to (a) receive a genuine LLM-rephrased, fact-grounded
 * summary on success — consistently in ~4-6s once the real {@code
 * "think": false} field was wired in (vs. 18-45+s and frequent timeouts
 * during the earlier {@code ChatClient}/prompt-suppression attempt), (b)
 * fall back cleanly and correctly on a timeout or malformed response, and
 * (c) leave the app fully bootable and usable with the LLM disabled (the
 * default).
 *
 * <p><b>Optional, never a hard dependency:</b> gated entirely by {@code
 * owi.llm.enabled} (default {@code false}); {@link #isAvailable()} reflects
 * that flag directly, since this class no longer depends on any
 * conditionally-created Spring bean the way a {@code ChatClient}-based
 * approach would.
 *
 * <p><b>Bounded call time:</b> a hung or slow local model call must never
 * hang the HTTP request indefinitely — {@link #REQUEST_TIMEOUT_SECONDS}
 * bounds it, with a timeout treated exactly like any other failure (falls
 * back).
 *
 * <p><b>Any failure — unreachable server, malformed/non-JSON response, an
 * empty or implausibly long summary, a timeout — falls back to the
 * deterministic {@link Insight} unchanged.</b> Never a thrown exception,
 * never a half-formed response; see {@link #tryRephraseSummary}.
 */
@Service
public class LlmInsightService {

    private static final Logger log = LoggerFactory.getLogger(LlmInsightService.class);

    // Live-tested this session against a real local Ollama 0.32.15 + the
    // configured default model (qwen3:8b) on CPU-only inference (no GPU
    // passthrough into the Docker container), with the real "think": false
    // request field wired in (see class Javadoc): repeated identical
    // requests consistently completed in ~4-6s. 30s leaves real headroom
    // above that observed baseline for slower hardware or a loaded machine,
    // without making a user wait anywhere near as long as the pre-fix
    // 18-45+s thinking-mode runs this session found and fixed.
    private static final int REQUEST_TIMEOUT_SECONDS = 30;
    private static final int MAX_SUMMARY_LENGTH = 600;

    private static final String SYSTEM_PROMPT = """
            You are a wellness coach explaining an ALREADY-COMPUTED readiness score to its owner.
            You do not compute or know anything about the user beyond what is given to you below.
            Rewrite ONLY the summary sentence in a warm, encouraging, plain-language coaching voice.
            Rules, strictly enforced:
            - Cite ONLY the facts given below (the score, headline, factors, confidence). Never invent, guess, or restate a number that was not given to you.
            - Do not add medical advice, diagnoses, or claims beyond what the facts support.
            - Keep it to 1-3 sentences.
            - Respond with ONLY a single JSON object of the exact shape {"summary": "..."} — no markdown, no code fences, no other text.
            """;

    private final boolean enabled;
    private final String model;
    private final RestClient restClient;
    private final ObjectMapper objectMapper;
    private final ExecutorService executor;

    public LlmInsightService(
            RestClient.Builder restClientBuilder,
            ObjectMapper objectMapper,
            @Value("${owi.llm.enabled:false}") boolean enabled,
            @Value("${owi.llm.model:qwen3:8b}") String model,
            @Value("${owi.llm.base-url:http://127.0.0.1:11434}") String baseUrl
    ) {
        this.enabled = enabled;
        this.model = model;
        this.restClient = restClientBuilder.baseUrl(baseUrl).build();
        this.objectMapper = objectMapper;
        this.executor = Executors.newCachedThreadPool();
    }

    /** Whether the LLM path is configured at all — see class javadoc "Optional, never a hard dependency". */
    public boolean isAvailable() {
        return enabled;
    }

    /**
     * Attempts an LLM-rephrased summary for the given, already-computed
     * score/insight. Empty on ANY failure — see class javadoc. Never blocks
     * longer than {@value #REQUEST_TIMEOUT_SECONDS}s.
     */
    public Optional<String> tryRephraseSummary(ReadinessScore score, Insight deterministic) {
        if (!enabled) {
            return Optional.empty();
        }
        try {
            CompletableFuture<String> call = CompletableFuture.supplyAsync(
                    () -> callOllamaChat(score, deterministic), executor);
            String raw = call.get(REQUEST_TIMEOUT_SECONDS, TimeUnit.SECONDS);
            return parseAndValidate(raw);
        } catch (TimeoutException e) {
            log.warn("LLM rephrase timed out after {}s, using deterministic summary", REQUEST_TIMEOUT_SECONDS);
            return Optional.empty();
        } catch (Exception e) {
            log.warn("LLM rephrase failed, using deterministic summary: {}", e.getMessage(), e);
            return Optional.empty();
        }
    }

    /**
     * Raw POST to Ollama's {@code /api/chat} — see class javadoc for why
     * this bypasses Spring AI's {@code ChatClient}. {@code think=false} is
     * the whole reason this method exists rather than a three-line
     * {@code ChatClient} call.
     */
    private String callOllamaChat(ReadinessScore score, Insight deterministic) {
        ObjectNode body = objectMapper.createObjectNode();
        body.put("model", model);
        body.put("stream", false);
        body.put("think", false);
        var messages = body.putArray("messages");
        messages.addObject().put("role", "system").put("content", SYSTEM_PROMPT);
        messages.addObject().put("role", "user").put("content", buildUserPrompt(score, deterministic));

        JsonNode response = postToOllama(body);

        if (response == null) {
            throw new IllegalStateException("Ollama returned an empty response body");
        }
        JsonNode content = response.path("message").path("content");
        if (content.isMissingNode() || !content.isTextual()) {
            throw new IllegalStateException("Ollama response had no message.content field");
        }
        return content.asText();
    }

    /**
     * The actual HTTP call, isolated behind its own method so tests can
     * stub it directly (via {@code spy()}) rather than mocking {@link
     * RestClient}'s fluent interface — mocking that interface's multi-hop,
     * overloaded-method chain proved unreliable with both {@code
     * RETURNS_DEEP_STUBS} and explicit stepwise mocks (see the test class's
     * own comment). Package-private so {@code LlmInsightServiceTest} can spy it.
     */
    JsonNode postToOllama(ObjectNode body) {
        return restClient.post()
                .uri("/api/chat")
                .contentType(org.springframework.http.MediaType.APPLICATION_JSON)
                .body(body)
                .retrieve()
                .body(JsonNode.class);
    }

    private String buildUserPrompt(ReadinessScore score, Insight deterministic) {
        StringJoiner factors = new StringJoiner("; ");
        for (FactorSummary f : deterministic.supportingFactors()) {
            factors.add(f.name() + " = " + f.value() + " (" + f.direction() + ")");
        }
        return String.format(Locale.ROOT, """
                Score: %d/100
                Headline: %s
                Factors: %s
                Confidence: %s
                Original deterministic summary (rewrite this, do not add new facts): %s
                """,
                score.score(), deterministic.headline(), factors, score.confidence(), deterministic.summary());
    }

    /** Package-private record matching the strict {"summary": "..."} shape the prompt demands. */
    private record LlmSummaryPayload(String summary) {}

    private Optional<String> parseAndValidate(String raw) {
        if (raw == null || raw.isBlank()) {
            return Optional.empty();
        }
        try {
            LlmSummaryPayload payload = objectMapper.readValue(extractJsonObject(raw), LlmSummaryPayload.class);
            if (payload.summary() == null || payload.summary().isBlank()) {
                return Optional.empty();
            }
            String summary = payload.summary().trim();
            if (summary.length() > MAX_SUMMARY_LENGTH) {
                log.warn("LLM summary exceeded {} chars, using deterministic summary", MAX_SUMMARY_LENGTH);
                return Optional.empty();
            }
            return Optional.of(summary);
        } catch (Exception e) {
            log.warn("LLM response was not the expected JSON shape, using deterministic summary: {}", e.getMessage());
            return Optional.empty();
        }
    }

    /**
     * Local models frequently wrap JSON in prose or markdown code fences
     * despite instructions not to — extracts the first {@code {...}} object
     * rather than requiring the whole response to be bare JSON. Returns the
     * input unchanged if no braces are found (parsing then fails cleanly).
     */
    private String extractJsonObject(String raw) {
        int start = raw.indexOf('{');
        int end = raw.lastIndexOf('}');
        if (start >= 0 && end > start) {
            return raw.substring(start, end + 1);
        }
        return raw;
    }
}
