package com.openwearableinsights.api.insights.application;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.openwearableinsights.api.insights.application.DeterministicInsightEngine.CitedMetric;
import com.openwearableinsights.api.insights.application.DeterministicInsightEngine.FactorSummary;
import com.openwearableinsights.api.insights.application.DeterministicInsightEngine.HabitCue;
import com.openwearableinsights.api.insights.application.DeterministicInsightEngine.Insight;
import com.openwearableinsights.api.insights.application.DeterministicInsightEngine.WhyAnswer;
import com.openwearableinsights.api.readiness.domain.ReadinessScore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.util.Locale;
import java.util.Optional;
import java.util.StringJoiner;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

/**
 * Optional local-LLM rephrasing of the coach's deterministic outputs — backs
 * docs/product/release-plan.md Phase 1 acceptance criteria #10/#11
 * ("optionally produces a local Ollama explanation" / "works when Ollama is
 * unavailable") and {@code owi.llm.enabled} (see {@code CoachController}).
 * Covers all three coach touchpoints: the daily {@link Insight}'s summary,
 * the {@link WhyAnswer}'s answer, and a {@link HabitCue}'s reasoning — the
 * same proven pattern applied everywhere the coach speaks to the user,
 * rather than on just one card.
 *
 * <p><b>Strictly a phrasing layer, never a second source of facts:</b> for
 * every one of the three touchpoints, the LLM is given only the
 * already-computed facts (score, factors/cited-metrics, confidence) and
 * asked to rewrite ONLY the existing deterministic text in a warmer coaching
 * voice — citing the same facts already given, never a new number, factor,
 * or claim. This is not a stylistic preference: {@link ReadinessScore}'s own
 * class javadoc states the project's core principle ("generated by
 * deterministic, testable analytics code — never by an LLM. The LLM may
 * explain this score; it never invents or overrides it") and {@code
 * DeterministicInsightEngine}'s own javadoc repeats it. Every other field on
 * the returned record is always copied verbatim from the deterministic
 * engine's own output — only the one text field can differ.
 *
 * <p><b>Talks to Ollama's REST API directly, not via Spring AI's {@code
 * ChatClient}:</b> a deliberate choice, made after live-testing this session
 * against a real local Ollama 0.32.15 server + the configured default model
 * (qwen3:8b — the {@code OWI_LLM_MODEL} default in {@code application.yml}).
 * Qwen3 models "think" (an internal chain-of-thought, 900+ tokens observed
 * live) before answering by default, which is wildly disproportionate for a
 * one-sentence rephrase — a first attempt at suppressing it via a {@code
 * /no_think} prompt-level directive (Qwen3's own documented convention)
 * measurably helped but did not reliably eliminate it. Ollama's own {@code
 * /api/chat} added a native {@code "think": false} request field for exactly
 * this, which reliably works — but Spring AI 1.0.1's {@code OllamaOptions}
 * has no field for it and no generic passthrough for undocumented Ollama
 * options (confirmed by inspecting its full field list), so it cannot be
 * expressed through {@code ChatClient} at all. A plain {@link RestClient}
 * call to {@code /api/chat} with the real JSON field {@code "think": false}
 * is the only way to reliably suppress it at this Spring AI version.
 *
 * <p><b>Live-verified this session</b> (not merely unit-tested against
 * mocks): a real local Ollama 0.32.15 server was brought up via {@code
 * infrastructure/docker/docker-compose.yml}'s optional {@code llm} profile,
 * {@code qwen3:8b} was pulled, and real requests through this exact class
 * were confirmed to (a) receive a genuine LLM-rephrased, fact-grounded
 * result on success — consistently in ~4-7s once the real {@code
 * "think": false} field was wired in, (b) fall back cleanly and correctly on
 * a timeout or malformed response, and (c) leave the app fully bootable and
 * usable with the LLM disabled (the default).
 *
 * <p><b>Optional, never a hard dependency:</b> gated entirely by {@code
 * owi.llm.enabled} (default {@code false}); {@link #isAvailable()} reflects
 * that flag directly.
 *
 * <p><b>Bounded call time:</b> a hung or slow local model call must never
 * hang the HTTP request indefinitely — {@link #REQUEST_TIMEOUT_SECONDS}
 * bounds it, with a timeout treated exactly like any other failure (falls
 * back).
 *
 * <p><b>Any failure — unreachable server, malformed/non-JSON response, an
 * empty or implausibly long result, a timeout — falls back to the
 * deterministic text unchanged.</b> Never a thrown exception, never a
 * half-formed response; see {@link #attemptRephrase}.
 */
@Service
public class LlmInsightService {

    private static final Logger log = LoggerFactory.getLogger(LlmInsightService.class);

    // Live-tested this session against a real local Ollama 0.32.15 + the
    // configured default model (qwen3:8b) on CPU-only inference (no GPU
    // passthrough into the Docker container), with the real "think": false
    // request field wired in (see class Javadoc): repeated identical
    // requests consistently completed in ~4-7s across all three touchpoints
    // (daily insight, why-answer, habit-cue). 30s leaves real headroom above
    // that observed baseline for slower hardware or a loaded machine.
    private static final int REQUEST_TIMEOUT_SECONDS = 30;
    private static final int MAX_TEXT_LENGTH = 700;

    private static final String SYSTEM_PROMPT = """
            You are a wellness coach explaining an ALREADY-COMPUTED result to its owner.
            You do not compute or know anything about the user beyond what is given to you below.
            Rewrite ONLY the given original text in a warm, encouraging, plain-language coaching voice.
            Rules, strictly enforced:
            - Cite ONLY the facts given below. Never invent, guess, or restate a number that was not given to you.
            - Do not add medical advice, diagnoses, or claims beyond what the facts support.
            - Keep roughly the same length as the original text — do not pad it out.
            - Respond with ONLY a single JSON object of the exact shape {"text": "..."} — no markdown, no code fences, no other text.
            """;

    private final boolean enabled;
    private final String model;
    private final RestClient restClient;
    private final ObjectMapper objectMapper;
    private final ExecutorService executor;

    public LlmInsightService(
            RestClient.Builder restClientBuilder,
            ObjectMapper objectMapper,
            @Value("${owi.llm.enabled:false}") boolean enabled,
            @Value("${owi.llm.model:qwen3:8b}") String model,
            @Value("${owi.llm.base-url:http://127.0.0.1:11434}") String baseUrl
    ) {
        this.enabled = enabled;
        this.model = model;
        this.restClient = restClientBuilder.baseUrl(baseUrl).build();
        this.objectMapper = objectMapper;
        this.executor = Executors.newCachedThreadPool();
    }

    /** Whether the LLM path is configured at all — see class javadoc "Optional, never a hard dependency". */
    public boolean isAvailable() {
        return enabled;
    }

    /** Attempts an LLM-rephrased daily-insight summary. Empty on ANY failure — see class javadoc. */
    public Optional<String> tryRephraseSummary(ReadinessScore score, Insight deterministic) {
        return attemptRephrase(buildInsightPrompt(score, deterministic));
    }

    /** Attempts an LLM-rephrased "why" answer. Empty on ANY failure — see class javadoc. */
    public Optional<String> tryRephraseWhyAnswer(ReadinessScore score, WhyAnswer deterministic) {
        return attemptRephrase(buildWhyAnswerPrompt(score, deterministic));
    }

    /** Attempts an LLM-rephrased habit-cue reasoning line. Empty on ANY failure — see class javadoc. */
    public Optional<String> tryRephraseHabitCue(HabitCue deterministic) {
        return attemptRephrase(buildHabitCuePrompt(deterministic));
    }

    /**
     * Shared core for all three touchpoints: disabled check, bounded async
     * call, and response parsing/validation. Never blocks longer than
     * {@value #REQUEST_TIMEOUT_SECONDS}s.
     */
    private Optional<String> attemptRephrase(String userPrompt) {
        if (!enabled) {
            return Optional.empty();
        }
        try {
            CompletableFuture<String> call = CompletableFuture.supplyAsync(
                    () -> callOllamaChat(userPrompt), executor);
            String raw = call.get(REQUEST_TIMEOUT_SECONDS, TimeUnit.SECONDS);
            return parseAndValidate(raw);
        } catch (TimeoutException e) {
            log.warn("LLM rephrase timed out after {}s, using deterministic text", REQUEST_TIMEOUT_SECONDS);
            return Optional.empty();
        } catch (Exception e) {
            log.warn("LLM rephrase failed, using deterministic text: {}", e.getMessage(), e);
            return Optional.empty();
        }
    }

    /**
     * Raw POST to Ollama's {@code /api/chat} — see class javadoc for why
     * this bypasses Spring AI's {@code ChatClient}. {@code think=false} is
     * the whole reason this method exists rather than a three-line
     * {@code ChatClient} call.
     */
    private String callOllamaChat(String userPrompt) {
        ObjectNode body = objectMapper.createObjectNode();
        body.put("model", model);
        body.put("stream", false);
        body.put("think", false);
        var messages = body.putArray("messages");
        messages.addObject().put("role", "system").put("content", SYSTEM_PROMPT);
        messages.addObject().put("role", "user").put("content", userPrompt);

        JsonNode response = postToOllama(body);

        if (response == null) {
            throw new IllegalStateException("Ollama returned an empty response body");
        }
        JsonNode content = response.path("message").path("content");
        if (content.isMissingNode() || !content.isTextual()) {
            throw new IllegalStateException("Ollama response had no message.content field");
        }
        return content.asText();
    }

    /**
     * The actual HTTP call, isolated behind its own method so tests can
     * stub it directly (via {@code spy()}) rather than mocking {@link
     * RestClient}'s fluent interface — mocking that interface's multi-hop,
     * overloaded-method chain proved unreliable with both {@code
     * RETURNS_DEEP_STUBS} and explicit stepwise mocks (see the test class's
     * own comment). Package-private so {@code LlmInsightServiceTest} can spy it.
     */
    JsonNode postToOllama(ObjectNode body) {
        return restClient.post()
                .uri("/api/chat")
                .contentType(org.springframework.http.MediaType.APPLICATION_JSON)
                .body(body)
                .retrieve()
                .body(JsonNode.class);
    }

    private String buildInsightPrompt(ReadinessScore score, Insight deterministic) {
        StringJoiner factors = new StringJoiner("; ");
        for (FactorSummary f : deterministic.supportingFactors()) {
            factors.add(f.name() + " = " + f.value() + " (" + f.direction() + ")");
        }
        return String.format(Locale.ROOT, """
                Score: %d/100
                Headline: %s
                Factors: %s
                Confidence: %s
                Original text to rewrite (do not add new facts): %s
                """,
                score.score(), deterministic.headline(), factors, score.confidence(), deterministic.summary());
    }

    private String buildWhyAnswerPrompt(ReadinessScore score, WhyAnswer deterministic) {
        StringJoiner metrics = new StringJoiner("; ");
        for (CitedMetric m : deterministic.citedMetrics()) {
            metrics.add(m.name() + " = " + m.value() + " (contribution " + m.contribution() + ", " + m.direction() + ")");
        }
        return String.format(Locale.ROOT, """
                Score: %d/100
                Cited metrics: %s
                Confidence: %s
                Original text to rewrite (do not add new facts): %s
                """,
                score.score(), metrics, deterministic.confidence(), deterministic.answer());
    }

    private String buildHabitCuePrompt(HabitCue deterministic) {
        return String.format(Locale.ROOT, """
                Trigger factor: %s (contribution %.1f)
                Suggested category: %s
                Suggested behavior: %s
                Confidence: %s
                Original text to rewrite (do not add new facts): %s
                """,
                deterministic.triggerFactor(), deterministic.triggerContribution(),
                deterministic.suggestedCategory(), deterministic.suggestedBehavior(),
                deterministic.confidence(), deterministic.reasoning());
    }

    /** Package-private record matching the strict {"text": "..."} shape the prompt demands. */
    private record LlmTextPayload(String text) {}

    private Optional<String> parseAndValidate(String raw) {
        if (raw == null || raw.isBlank()) {
            return Optional.empty();
        }
        try {
            LlmTextPayload payload = objectMapper.readValue(extractJsonObject(raw), LlmTextPayload.class);
            if (payload.text() == null || payload.text().isBlank()) {
                return Optional.empty();
            }
            String text = payload.text().trim();
            if (text.length() > MAX_TEXT_LENGTH) {
                log.warn("LLM text exceeded {} chars, using deterministic text", MAX_TEXT_LENGTH);
                return Optional.empty();
            }
            return Optional.of(text);
        } catch (Exception e) {
            log.warn("LLM response was not the expected JSON shape, using deterministic text: {}", e.getMessage());
            return Optional.empty();
        }
    }

    /**
     * Local models frequently wrap JSON in prose or markdown code fences
     * despite instructions not to — extracts the first {@code {...}} object
     * rather than requiring the whole response to be bare JSON. Returns the
     * input unchanged if no braces are found (parsing then fails cleanly).
     */
    private String extractJsonObject(String raw) {
        int start = raw.indexOf('{');
        int end = raw.lastIndexOf('}');
        if (start >= 0 && end > start) {
            return raw.substring(start, end + 1);
        }
        return raw;
    }
}
